"""
Django settings for stickers_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dotenv
import os

dotenv.load_dotenv(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET")
PASSWORD_ATTEMPT_LIMIT = int(os.getenv("PASSWORD_ATTEMPT_LIMIT"))
PASSWORD_ATTEMPT_BAN_LIMIT = int(os.getenv("PASSWORD_ATTEMPT_BAN_LIMIT"))
TURNSTILE_SECRET = os.getenv("TURNSTILE_SECRET")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GIT_USERNAME = os.getenv("GIT_USERNAME")
GIT_PASSWORD = os.getenv("GIT_PASSWORD")
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
DISCORD_KEY = os.getenv("DISCORD_KEY")
DISCORD_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CALLBACK = os.getenv("DISCORD_CALLBACK")
MAX_UPLOAD_SIZE = int(os.getenv("MAX_UPLOAD_SIZE"))
MAX_USER_STORAGE = int(os.getenv("MAX_USER_STORAGE"))

AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]

AWS_S3_ENDPOINT_URL = os.environ["AWS_S3_ENDPOINT_URL"]

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_S3_ADDRESSING_STYLE = "path"
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "1"
debug = r"""
Service started
V----------------------------------------------------V
  _____       _                 
 |  __ \     | |                
 | |  | | ___| |__  _   _  __ _ 
 | |  | |/ _ \ '_ \| | | |/ _` |
 | |__| |  __/ |_) | |_| | (_| |
 |_____/ \___|_.__/ \__,_|\__, |
                           __/ |
                          |___/ 
"""

production = r"""
Service started
V----------------------------------------------------V
  _____               _            _   _             
 |  __ \             | |          | | (_)            
 | |__) | __ ___   __| |_   _  ___| |_ _  ___  _ __  
 |  ___/ '__/ _ \ / _` | | | |/ __| __| |/ _ \| '_ \ 
 | |   | | | (_) | (_| | |_| | (__| |_| | (_) | | | |
 |_|   |_|  \___/ \__,_|\__,_|\___|\__|_|\___/|_| |_|


"""

print(debug if DEBUG else production)

ALLOWED_HOSTS = ["*"]
# Cookies
if DEBUG:
    SESSION_COOKIE_SAMESITE = None   # default Lax
    SESSION_COOKIE_SECURE = False    # allow HTTP
    CSRF_COOKIE_SAMESITE = None
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",   # frontend origin
    "http://localhost:5173",   # frontend origin
    "https://subrectal-consanguineously-sammy.ngrok-free.app",
    "https://*.loca.lt",
    "https://oizqk-37-76-46-208.a.free.pinggy.link",
    "https://aether.sitespectrum.dev",
]
CORS_ALLOW_CREDENTIALS = True
# Application definition
CSRF_TRUSTED_ORIGINS = [
    "https://aether.sitespectrum.dev",
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'qsessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_extensions',
    'storages',
    'api',
    'authenticate',
    'site_admin',
    'notes',
    'bookmarks',
    'media',
    'django_cleanup.apps.CleanupConfig',
]

USE_X_FORWARDED_HOST = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'stickers_backend.middleware.RealIPMiddleware',
    'qsessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'stickers_backend.middleware.CustomExceptionHandlerMiddleware',
]

SESSION_ENGINE = "qsessions.backends.db"

LOGIN_REDIRECT_URL = "/dashboard"
LOGIN_URL = "/auth/login"

ROOT_URLCONF = 'stickers_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stickers_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
